# Usage: -DDEVICE_PROFILE=h2 -DDEVICE_PROFILE_VARIANT=sed
# Sleepy End Device — MTD with light sleep, battery-friendly
# Polls parent every THREAD_DEVICE_POLL_PERIOD_MS ms, sleeps between polls

CONFIG_OPENTHREAD_MTD=y

# Light sleep power management
CONFIG_PM_ENABLE=y
CONFIG_FREERTOS_USE_TICKLESS_IDLE=y
CONFIG_IEEE802154_SLEEP_ENABLE=y
CONFIG_PM_POWER_DOWN_PERIPHERAL_IN_LIGHT_SLEEP=y
CONFIG_ESP_SLEEP_POWER_DOWN_FLASH=y
CONFIG_FREERTOS_HZ=1000

# MTD doesn't need IPv4
CONFIG_LWIP_IPV4=n
CONFIG_LWIP_ND6=n
